"""add_deadline_to_jobs

Revision ID: 042faafe71e5
Revises: dc7eb3001b15
Create Date: 2026-01-15 00:38:55.002389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042faafe71e5'
down_revision = 'dc7eb3001b15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('deadline')

    # ### end Alembic commands ###
