"""Add cv_id to education experience skills languages certifications tables

Revision ID: 07c62b2cb6c1
Revises: b1b7c68c41a2
Create Date: 2026-01-14 22:02:56.090859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c62b2cb6c1'
down_revision = 'b1b7c68c41a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'cvs', ['cv_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('cvs', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    with op.batch_alter_table('educations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'cvs', ['cv_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'cvs', ['cv_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'cvs', ['cv_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'cvs', ['cv_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cv_id')

    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cv_id')

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cv_id')

    with op.batch_alter_table('educations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cv_id')

    with op.batch_alter_table('cvs', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cv_id')

    # ### end Alembic commands ###
