"""Add password reset fields to users table

Revision ID: 54408ba64172
Revises: 9e80a694d84a
Create Date: 2026-01-14 02:34:00.508616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54408ba64172'
down_revision = '9e80a694d84a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
