"""add_manual_job_fields_to_applications

Revision ID: 75115e499998
Revises: 042faafe71e5
Create Date: 2026-01-15 00:57:45.280568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75115e499998'
down_revision = '042faafe71e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('company', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('salary', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('job_type', sa.String(length=50), nullable=True))
        batch_op.alter_column('job_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('unique_user_job_application'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_user_job_application'), ['user_id', 'job_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('job_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('job_type')
        batch_op.drop_column('salary')
        batch_op.drop_column('location')
        batch_op.drop_column('company')
        batch_op.drop_column('job_title')

    # ### end Alembic commands ###
