"""Add contact fields to jobs table

Revision ID: 7f95b1b98e8a
Revises: 8d934a7b1d25
Create Date: 2026-01-15 13:29:34.781431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f95b1b98e8a'
down_revision = '8d934a7b1d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('website')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('contact_email')

    # ### end Alembic commands ###
