"""add_extracted_email_to_cvs

Revision ID: 8d934a7b1d25
Revises: b7983a6287f8
Create Date: 2026-01-15 01:56:37.349040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d934a7b1d25'
down_revision = 'b7983a6287f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cvs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cvs', schema=None) as batch_op:
        batch_op.drop_column('extracted_email')

    # ### end Alembic commands ###
