"""add extracted data fields to CV table

Revision ID: 9c68f8834c16
Revises: 07c62b2cb6c1
Create Date: 2026-01-14 22:41:17.234759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c68f8834c16'
down_revision = '07c62b2cb6c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cvs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_fullname', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('extracted_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('extracted_location', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extracted_summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cvs', schema=None) as batch_op:
        batch_op.drop_column('extracted_summary')
        batch_op.drop_column('extracted_location')
        batch_op.drop_column('extracted_phone')
        batch_op.drop_column('extracted_fullname')

    # ### end Alembic commands ###
