"""drop_obsolete_tables_add_cv_builder_data

Revision ID: b7983a6287f8
Revises: 75115e499998
Create Date: 2026-01-15 01:46:47.706270

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7983a6287f8'
down_revision = '75115e499998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certifications')
    op.drop_table('educations')
    op.drop_table('experiences')
    op.drop_table('languages')
    op.drop_table('contact_messages')
    op.drop_table('skills')
    with op.batch_alter_table('cvs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_builder_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cvs', schema=None) as batch_op:
        batch_op.drop_column('cv_builder_data')

    op.create_table('skills',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cv_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cvs.id'], name=op.f('skills_cv_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('skills_profile_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('skills_pkey'))
    )
    op.create_table('contact_messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('contact_messages_pkey'))
    )
    op.create_table('languages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('proficiency', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('cv_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cvs.id'], name=op.f('languages_cv_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('languages_profile_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('languages_pkey'))
    )
    op.create_table('experiences',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('duration', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cv_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cvs.id'], name=op.f('experiences_cv_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('experiences_profile_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('experiences_pkey'))
    )
    op.create_table('educations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('degree', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('institution', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('year', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cv_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cvs.id'], name=op.f('educations_cv_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('educations_profile_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('educations_pkey'))
    )
    op.create_table('certifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('organization', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('year', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cv_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cvs.id'], name=op.f('certifications_cv_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('certifications_profile_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('certifications_pkey'))
    )
    # ### end Alembic commands ###
