"""add extracted_data JSON to CV

Revision ID: bd140d592426
Revises: 9c68f8834c16
Create Date: 2026-01-14 22:50:45.787886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd140d592426'
down_revision = '9c68f8834c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cvs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cvs', schema=None) as batch_op:
        batch_op.drop_column('extracted_data')

    # ### end Alembic commands ###
