"""Add email column to profiles table

Revision ID: c782d05b6ad9
Revises: add_job_notifications_001
Create Date: 2026-01-16 10:53:39.965337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c782d05b6ad9'
down_revision = 'add_job_notifications_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_notifications_notification_type'))
        batch_op.drop_index(batch_op.f('ix_job_notifications_user_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_notifications_notification_type'), ['notification_type'], unique=False)

    # ### end Alembic commands ###
